# -*- coding: utf-8 -*-
"""EXTRACTION.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LBu7A9r7Gz1hlfS8PTXNXJiKDEMHjShg
"""



"""# Version validée"""

# SUJET : Extraction d'entités → Graphe RDF (avec rdflib) + Visualisation

!pip install kagglehub spacy rdflib networkx matplotlib
!python -m spacy download en_core_web_sm

import kagglehub
import os
import spacy
import networkx as nx
import matplotlib.pyplot as plt
import pandas as pd
import glob
import re
from rdflib import Graph, Namespace, URIRef, Literal, RDF, RDFS
from rdflib.namespace import FOAF, XSD

# ------------------------------
# 1. Chargement du texte (ex: un CV)
# ------------------------------
path = kagglehub.dataset_download("snehaanbhawal/resume-dataset")
csv_path = glob.glob(os.path.join(path, "**", "Resume.csv"), recursive=True)[0]
df = pd.read_csv(csv_path)
resume_text_column = 'Resume_str' if 'Resume_str' in df.columns else 'resume_str'

cv_index = 1  # Tu peux changer pour tester d'autres CVs
row = df.iloc[cv_index]
resume_text = str(row[resume_text_column])
resume_id = row.get('ID', cv_index + 1)

print(f"Analyse du CV n°{cv_index + 1} (ID: {resume_id})\n")

# ------------------------------
# 2. spaCy pour extraction ML
# ------------------------------
nlp = spacy.load("en_core_web_sm")
doc = nlp(resume_text)

# ------------------------------
# 3. Définition des namespaces RDF
# ------------------------------
EX = Namespace("http://example.org/resume/")
SCHEMA = Namespace("http://schema.org/")
g = Graph()
g.bind("ex", EX)
g.bind("schema", SCHEMA)
g.bind("foaf", FOAF)

# Sujet principal : le CV ou la personne
resume_uri = EX[f"resume_{resume_id}"]
person_uri = EX[f"person_{resume_id}"]

# On lie le CV à une personne (foaf:Person)
g.add((resume_uri, RDF.type, SCHEMA.JobPosting))
g.add((resume_uri, SCHEMA.about, person_uri))
g.add((person_uri, RDF.type, FOAF.Person))

# ------------------------------
# 4. Extraction et création de TRIPLETS RDF
# ------------------------------
# Organisations
for org_text in {ent.text.strip() for ent in doc.ents if ent.label_ == "ORG"}:
    org_uri = EX[f"org_{org_text.replace(' ', '_')}_{hash(org_text) % 10000}"]
    g.add((org_uri, RDF.type, SCHEMA.Organization))
    g.add((org_uri, SCHEMA.name, Literal(org_text, datatype=XSD.string)))
    g.add((person_uri, SCHEMA.alumniOf, org_uri))  # ou worksFor selon contexte
    g.add((person_uri, SCHEMA.knowsAbout, org_uri))  # relation générique

# Langues
for lang in {ent.text.strip() for ent in doc.ents if ent.label_ == "LANGUAGE"}:
    g.add((person_uri, SCHEMA.knowsLanguage, Literal(lang, datatype=XSD.string)))

# Compétences (skills) - via keywords
skill_keywords = ["Python", "Java", "SQL", "Machine Learning", "Deep Learning", "AWS", "Docker", "React", "Excel", "Tableau", "Git"]
for skill in skill_keywords:
    if skill.lower() in resume_text.lower():
        skill_uri = EX[f"skill_{skill.replace(' ', '_')}"]
        g.add((skill_uri, RDF.type, SCHEMA.Skill))
        g.add((skill_uri, RDFS.label, Literal(skill)))
        g.add((person_uri, SCHEMA.hasSkill, skill_uri))

# Rôles (ex: Data Scientist)
role_pattern = re.search(r"\b(Data Scientist|Software Engineer|Machine Learning Engineer|Data Analyst)\b", resume_text, re.I)
if role_pattern:
    role = role_pattern.group(0)
    g.add((person_uri, SCHEMA.jobTitle, Literal(role, datatype=XSD.string)))

# Domaine d'étude
field_pattern = re.search(r"\b(Computer Science|Data Science|Engineering|Business Administration)\b", resume_text, re.I)
if field_pattern:
    field = field_pattern.group(0)
    g.add((person_uri, SCHEMA.alumniOf, Literal(field, datatype=XSD.string)))

# ------------------------------
# 5. Affichage des triplets RDF (exemple)
# ------------------------------
print("=== Exemple de triplets RDF générés ===")
for s, p, o in list(g)[:15]:
    print(f"{s.n3()} → {p.n3()} → {o.n3()}")
print(f"... et {len(g) - 15} autres triplets\n")
print(f"Total : {len(g)} triplets RDF\n")

# ------------------------------
# 6. Visualisation du graphe RDF
# ------------------------------
G_vis = nx.DiGraph()

for s, p, o in g:
    s_label = s.n3().split("/")[-1].strip(">")
    o_label = o if isinstance(o, URIRef) else str(o)
    o_label = o_label.split("/")[-1].strip(">") if isinstance(o, URIRef) else str(o)
    p_label = p.n3().split("/")[-1].split("}")[0].strip(">")

    G_vis.add_node(s_label)
    G_vis.add_node(o_label)
    G_vis.add_edge(s_label, o_label, label=p_label)

plt.figure(figsize=(18, 12))
pos = nx.spring_layout(G_vis, k=1.5, iterations=80, seed=42)

# Couleurs
node_colors = ["#DD6B4D" if "person" in n.lower() or "resume" in n.lower() else "#55A3D9" for n in G_vis.nodes()]
nx.draw_networkx_nodes(G_vis, pos, node_color=node_colors, node_size=2500, edgecolors="black")

nx.draw_networkx_edges(G_vis, pos, arrows=True, arrowstyle="->", arrowsize=20, width=1.5)

nx.draw_networkx_labels(G_vis, pos, font_size=10, font_weight="bold")

edge_labels = nx.get_edge_attributes(G_vis, 'label')
nx.draw_networkx_edge_labels(G_vis, pos, edge_labels=edge_labels, font_color="red", font_size=9)

plt.title("Graphe RDF : Extraction d'entités à partir d'un CV\n(Triplets Sujet → Prédicat → Objet)", fontsize=16)
plt.axis("off")
plt.tight_layout()
plt.show()

# Bonus : Export RDF (pour réutilisation)
g.serialize(destination="resume_knowledge_graph.ttl", format="turtle")
print("Graphe RDF exporté au format Turtle : resume_knowledge_graph.ttl")

"""VERSION ENRICHIE avec plus de skills et de domaine  """

# SUJET : Extraction d'entités → Graphe RDF (avec rdflib) + Visualisation
# =========================================================
!pip install kagglehub spacy rdflib networkx matplotlib
!python -m spacy download en_core_web_sm
import kagglehub
import os
import spacy
import networkx as nx
import matplotlib.pyplot as plt
import pandas as pd
import glob
import re
from rdflib import Graph, Namespace, URIRef, Literal, RDF, RDFS
from rdflib.namespace import FOAF, XSD
# ------------------------------
# 1. Chargement du texte (ex: un CV)
# ------------------------------
path = kagglehub.dataset_download("snehaanbhawal/resume-dataset")
csv_path = glob.glob(os.path.join(path, "**", "Resume.csv"), recursive=True)[0]
df = pd.read_csv(csv_path)
resume_text_column = 'Resume_str' if 'Resume_str' in df.columns else 'resume_str'
cv_index = 0 # Tu peux changer pour tester d'autres CVs
row = df.iloc[cv_index]
resume_text = str(row[resume_text_column])
resume_id = row.get('ID', cv_index + 1)
print(f"Analyse du CV n°{cv_index + 1} (ID: {resume_id})\n")
# ------------------------------
# 2. spaCy pour extraction ML
# ------------------------------
nlp = spacy.load("en_core_web_sm")
doc = nlp(resume_text)
# ------------------------------
# 3. Définition des namespaces RDF
# ------------------------------
EX = Namespace("http://example.org/resume/")
SCHEMA = Namespace("http://schema.org/")
g = Graph()
g.bind("ex", EX)
g.bind("schema", SCHEMA)
g.bind("foaf", FOAF)
# Sujet principal : le CV ou la personne
resume_uri = EX[f"resume_{resume_id}"]
person_uri = EX[f"person_{resume_id}"]
# On lie le CV à une personne (foaf:Person)
g.add((resume_uri, RDF.type, SCHEMA.JobPosting))
g.add((resume_uri, SCHEMA.about, person_uri))
g.add((person_uri, RDF.type, FOAF.Person))
# ------------------------------
# 4. Extraction et création de TRIPLETS RDF
# ------------------------------
# Organisations
for org_text in {ent.text.strip() for ent in doc.ents if ent.label_ == "ORG"}:
    org_uri = EX[f"org_{org_text.replace(' ', '_')}_{hash(org_text) % 10000}"]
    g.add((org_uri, RDF.type, SCHEMA.Organization))
    g.add((org_uri, SCHEMA.name, Literal(org_text, datatype=XSD.string)))
    g.add((person_uri, SCHEMA.alumniOf, org_uri)) # ou worksFor selon contexte
    g.add((person_uri, SCHEMA.knowsAbout, org_uri)) # relation générique
# Langues
for lang in {ent.text.strip() for ent in doc.ents if ent.label_ == "LANGUAGE"}:
    g.add((person_uri, SCHEMA.knowsLanguage, Literal(lang, datatype=XSD.string)))
# Compétences (skills) - via keywords enrichis
skill_keywords = [
    "Python", "Java", "SQL", "Machine Learning", "Deep Learning", "AWS", "Docker", "React", "Excel", "Tableau", "Git",
    "C++", "JavaScript", "HTML", "CSS", "Kubernetes", "TensorFlow", "PyTorch", "R", "SAS", "Power BI",
    "Node.js", "Angular", "Vue.js", "Linux", "Agile", "Scrum", "DevOps", "CI/CD", "Big Data", "Hadoop",
    "Spark", "MongoDB", "MySQL", "PostgreSQL", "REST API", "GraphQL", "Jenkins", "Terraform", "Ansible",
    "Data Visualization", "Statistics", "Algorithms", "Data Structures", "Cloud Computing", "Cybersecurity",
    "Blockchain", "IoT", "Mobile Development", "Android", "iOS", "Swift", "Kotlin", "Flutter", "React Native"
]
for skill in skill_keywords:
    if skill.lower() in resume_text.lower():
        skill_uri = EX[f"skill_{skill.replace(' ', '_')}"]
        g.add((skill_uri, RDF.type, SCHEMA.Skill))
        g.add((skill_uri, RDFS.label, Literal(skill)))
        g.add((person_uri, SCHEMA.hasSkill, skill_uri))
# Rôles (ex: Data Scientist) - enrichis avec plus de titres et extraction multiple
role_keywords = [
    "Data Scientist", "Software Engineer", "Machine Learning Engineer", "Data Analyst",
    "Project Manager", "DevOps Engineer", "Full Stack Developer", "AI Engineer", "Business Analyst",
    "Product Manager", "UX Designer", "UI Developer", "Systems Administrator", "Network Engineer",
    "Database Administrator", "QA Engineer", "Security Analyst", "Cloud Architect", "Data Engineer",
    "Frontend Developer", "Backend Developer", "Mobile Developer", "Research Scientist", "Consultant",
    "Marketing Specialist", "Sales Manager", "HR Specialist", "Financial Analyst", "Operations Manager"
]
role_pattern = re.findall(r"\b(" + "|".join(role_keywords) + r")\b", resume_text, re.I)
for role in set(role.lower() for role in role_pattern):
    g.add((person_uri, SCHEMA.jobTitle, Literal(role.capitalize(), datatype=XSD.string)))
# Domaine d'étude - enrichis avec plus de domaines et extraction multiple
field_keywords = [
    "Computer Science", "Data Science", "Engineering", "Business Administration",
    "Information Technology", "Mathematics", "Statistics", "Electrical Engineering",
    "Mechanical Engineering", "Finance", "Economics", "Physics", "Biology", "Chemistry",
    "Psychology", "Marketing", "Management", "Artificial Intelligence", "Cybersecurity",
    "Software Engineering", "Biomedical Engineering", "Environmental Science", "Graphic Design",
    "Human Resources", "Accounting", "Law", "Medicine", "Nursing", "Education"
]
field_pattern = re.findall(r"\b(" + "|".join(field_keywords) + r")\b", resume_text, re.I)
for field in set(field.lower() for field in field_pattern):
    field_uri = EX[f"field_{field.replace(' ', '_')}"]
    g.add((field_uri, RDF.type, SCHEMA.EducationalOccupationalProgram))
    g.add((field_uri, SCHEMA.name, Literal(field.capitalize(), datatype=XSD.string)))
    g.add((person_uri, SCHEMA.alumniOf, field_uri))
# ------------------------------
# 5. Affichage des triplets RDF (exemple)
# ------------------------------
print("=== Exemple de triplets RDF générés ===")
for s, p, o in list(g)[:15]:
    print(f"{s.n3()} → {p.n3()} → {o.n3()}")
print(f"... et {len(g) - 15} autres triplets\n")
print(f"Total : {len(g)} triplets RDF\n")
# ------------------------------
# 6. Visualisation du graphe RDF
# ------------------------------
G_vis = nx.DiGraph()
for s, p, o in g:
    s_label = s.n3().split("/")[-1].strip(">")
    o_label = o if isinstance(o, URIRef) else str(o)
    o_label = o_label.split("/")[-1].strip(">") if isinstance(o, URIRef) else str(o)
    p_label = p.n3().split("/")[-1].split("}")[0].strip(">")
    G_vis.add_node(s_label)
    G_vis.add_node(o_label)
    G_vis.add_edge(s_label, o_label, label=p_label)
plt.figure(figsize=(18, 12))
pos = nx.spring_layout(G_vis, k=1.5, iterations=80, seed=42)
# Couleurs
node_colors = ["#DD6B4D" if "person" in n.lower() or "resume" in n.lower() else "#55A3D9" for n in G_vis.nodes()]
nx.draw_networkx_nodes(G_vis, pos, node_color=node_colors, node_size=2500, edgecolors="black")
nx.draw_networkx_edges(G_vis, pos, arrows=True, arrowstyle="->", arrowsize=20, width=1.5)
nx.draw_networkx_labels(G_vis, pos, font_size=10, font_weight="bold")
edge_labels = nx.get_edge_attributes(G_vis, 'label')
nx.draw_networkx_edge_labels(G_vis, pos, edge_labels=edge_labels, font_color="red", font_size=9)
plt.title("Graphe RDF : Extraction d'entités à partir d'un CV\n(Triplets Sujet → Prédicat → Objet)", fontsize=16)
plt.axis("off")
plt.tight_layout()
plt.show()
# Export RDF (pour réutilisation)
# ------------------------------
g.serialize(destination="resume_knowledge_graph.ttl", format="turtle")
print("Graphe RDF exporté au format Turtle : resume_knowledge_graph.ttl")

"""Mieux extraire les rôles et Rendre le graphe plus *lisible*  réduire les faux positifs et mooins de doublons + changement de certains mots clés -> plus précis


"""

# SUJET : Extraction améliorée d'entités CV → Graphe RDF + Visualisation propre
# =========================================================
!pip install kagglehub spacy rdflib networkx matplotlib
!python -m spacy download en_core_web_sm
import kagglehub
import os
import spacy
import networkx as nx
import matplotlib.pyplot as plt
import pandas as pd
import glob
import re
from rdflib import Graph, Namespace, Literal, RDF, RDFS, URIRef
from rdflib.namespace import FOAF, XSD

# ------------------------------
# 1. Chargement du CV
# ------------------------------
path = kagglehub.dataset_download("snehaanbhawal/resume-dataset")
csv_path = glob.glob(os.path.join(path, "**", "Resume.csv"), recursive=True)[0]
df = pd.read_csv(csv_path)
resume_text_column = 'Resume_str' if 'Resume_str' in df.columns else 'resume_str'

cv_index = 0  # Change ici pour tester un autre CV
row = df.iloc[cv_index]
resume_text = str(row[resume_text_column]).lower()  # tout en minuscule pour les recherches
resume_text_original = str(row[resume_text_column])  # garde l'original pour affichage
resume_id = row.get('ID', cv_index + 1)

print(f"Analyse du CV n°{cv_index + 1} (ID: {resume_id})\n")

# ------------------------------
# 2. spaCy
# ------------------------------
nlp = spacy.load("en_core_web_sm")
doc = nlp(resume_text_original)  # on garde le texte original pour spaCy (meilleure détection)

# ------------------------------
# 3. Namespaces RDF
# ------------------------------
EX = Namespace("http://example.org/resume/")
SCHEMA = Namespace("http://schema.org/")
g = Graph()
g.bind("ex", EX)
g.bind("schema", SCHEMA)
g.bind("foaf", FOAF)

resume_uri = EX[f"resume_{resume_id}"]
person_uri = EX[f"person_{resume_id}"]

g.add((resume_uri, RDF.type, SCHEMA.JobPosting))
g.add((resume_uri, SCHEMA.about, person_uri))
g.add((person_uri, RDF.type, FOAF.Person))

# ------------------------------
# 4. Listes enrichies et améliorées
# ------------------------------

# Compétences techniques et outils (on les cherche en priorité)
skills_list = [
    "python", "java", "javascript", "sql", "excel", "powerpoint", "tableau", "power bi", "r",
    "machine learning", "deep learning", "tensorflow", "pytorch", "aws", "azure", "gcp",
    "docker", "kubernetes", "git", "react", "angular", "node.js", "html", "css",
    "agile", "scrum", "devops", "ci/cd", "linux", "mongodb", "mysql", "postgresql",
    "rest api", "graphql", "jenkins", "terraform", "ansible", "spark", "hadoop", "big data"
]

# Postes / Rôles professionnels
job_titles = [
    "data scientist", "software engineer", "machine learning engineer", "data analyst",
    "data engineer", "full stack developer", "frontend developer", "backend developer",
    "devops engineer", "cloud architect", "project manager", "product manager",
    "business analyst", "ux designer", "ui designer", "system administrator",
    "database administrator", "qa engineer", "security analyst", "hr manager", "recruiter"
]

# Domaines d'études
fields_of_study = [
    "computer science", "data science", "information technology", "software engineering",
    "electrical engineering", "mechanical engineering", "business administration",
    "finance", "economics", "mathematics", "statistics", "physics", "psychology",
    "marketing", "human resources", "organizational leadership", "education",
    "artificial intelligence", "cybersecurity"
]

# ------------------------------
# 5. Extraction améliorée
# ------------------------------

# 1. Compétences (priorité haute : on les ajoute uniquement comme skills)
detected_skills = set()
for skill in skills_list:
    if skill in resume_text:
        detected_skills.add(skill.title())
        skill_uri = EX[f"skill_{skill.replace(' ', '_').replace('-', '_')}"]
        g.add((skill_uri, RDF.type, SCHEMA.Skill))
        g.add((skill_uri, RDFS.label, Literal(skill.title())))
        g.add((person_uri, SCHEMA.knowsAbout, skill_uri))  # plus approprié que hasSkill

# 2. Postes occupés (recherche plus large et multiple)
detected_jobs = set()
for title in job_titles:
    if title in resume_text:
        detected_jobs.add(title.title())
        g.add((person_uri, SCHEMA.jobTitle, Literal(title.title(), datatype=XSD.string)))

# Si aucun trouvé dans la liste, on tente d'extraire via motifs autour de "experience"
# Modifie le regex pour s'assurer que group(1) existe si "experience" est trouvé
experience_section_match = re.search(r'experience\s*(.*?)(?=\s*(?:education|skills|summary|$))', resume_text, re.I | re.DOTALL)
if experience_section_match:
    exp_text = experience_section_match.group(1)
    if exp_text: # Ensure exp_text is not empty before searching within it
        # Cherche des titres en début de ligne ou après des dates
        potential_titles = re.findall(r'(?:^|\n)\s*([A-Za-z\s&]+(?:Engineer|Analyst|Manager|Developer|Scientist|Specialist|Architect|Administrator|Coordinator|Consultant))', exp_text, re.I)
        for t in potential_titles:
            clean_title = t.strip().title()
            if len(clean_title.split()) <= 5:  # évite les phrases trop longues
                detected_jobs.add(clean_title)
                g.add((person_uri, SCHEMA.jobTitle, Literal(clean_title, datatype=XSD.string)))

# 3. Domaines d'études
detected_fields = set()
for field in fields_of_study:
    if field in resume_text:
        detected_fields.add(field.title())
        field_uri = EX[f"field_{field.replace(' ', '_')}"]
        g.add((field_uri, RDF.type, SCHEMA.EducationalOccupationalProgram))
        g.add((field_uri, SCHEMA.name, Literal(field.title())))
        g.add((person_uri, SCHEMA.alumniOf, field_uri))

# 4. Établissements éducatifs (via spaCy + filtre)
education_keywords = ["university", "college", "institute", "school"]
for ent in doc.ents:
    if ent.label_ == "ORG":
        ent_lower = ent.text.lower()
        if any(kw in ent_lower for kw in education_keywords) and "microsoft" not in ent_lower and "excel" not in ent_lower:
            org_uri = EX[f"edu_{ent.text.replace(' ', '_')}_{hash(ent.text) % 10000}"]
            g.add((org_uri, RDF.type, SCHEMA.CollegeOrUniversity))
            g.add((org_uri, SCHEMA.name, Literal(ent.text)))
            g.add((person_uri, SCHEMA.alumniOf, org_uri))

# 5. Organisations professionnelles (expérience pro, hors éducation et faux positifs)
blacklist_org = ["excel", "powerpoint", "word", "outlook", "customer", "state", "responsible", "agile"]
for ent in doc.ents:
    if ent.label_ == "ORG":
        ent_lower = ent.text.lower()
        if (any(kw in ent_lower for kw in education_keywords) or
            any(bl in ent_lower for bl in blacklist_org)):
            continue  # on saute les écoles (déjà traitées) et les faux positifs
        org_uri = EX[f"org_{ent.text.replace(' ', '_')}_{hash(ent.text) % 10000}"]
        g.add((org_uri, RDF.type, SCHEMA.Organization))
        g.add((org_uri, SCHEMA.name, Literal(ent.text)))
        g.add((person_uri, SCHEMA.worksFor, org_uri))  # plus précis que alumniOf

# 6. Affichage résumé
# ------------------------------
print("=== RÉSUMÉ DE L'EXTRACTION ===")
print(f"Compétences détectées : {', '.join(sorted(detected_skills)) or 'Aucune'}")
print(f"Postes occupés : {', '.join(sorted(detected_jobs)) or 'Aucun détecté précisément'}")
print(f"Domaines d'études : {', '.join(sorted(detected_fields)) or 'Aucun'}")
print(f"\nTotal triplets RDF : {len(g)}\n")

# 7. Visualisation améliorée (plus lisible)
# ------------------------------
G_vis = nx.DiGraph()
for s, p, o in g:
    s_label = str(s).split("/")[-1].replace("_", " ")[:30]
    if isinstance(o, URIRef):
        o_label = str(o).split("/")[-1].replace("_", " ")[:30]
    else:
        o_label = str(o)[:30]
    p_label = str(p).split("/")[-1].split("}")[-1]

    G_vis.add_node(s_label)
    G_vis.add_node(o_label)
    G_vis.add_edge(s_label, o_label, label=p_label)

plt.figure(figsize=(20, 14))
pos = nx.spring_layout(G_vis, k=2, iterations=100, seed=42)

# Couleurs par type
node_colors = []
for node in G_vis.nodes():
    if "person" in node.lower() or "resume" in node.lower():
        node_colors.append("#E74C3C")  # rouge pour la personne
    elif "skill" in node.lower():
        node_colors.append("#3498DB")  # bleu pour compétences
    elif "field" in node.lower() or "edu_" in node:
        node_colors.append("#2ECC71")  # vert pour éducation
    elif "org_" in node:
        node_colors.append("#F39C12")  # orange pour entreprises
    else:
        node_colors.append("#95A5A6")

nx.draw_networkx_nodes(G_vis, pos, node_color=node_colors, node_size=3000, edgecolors="black", linewidths=1.5)
nx.draw_networkx_edges(G_vis, pos, arrows=True, arrowstyle="->", arrowsize=20, width=1.2, alpha=0.7)
nx.draw_networkx_labels(G_vis, pos, font_size=9, font_weight="bold")
edge_labels = nx.get_edge_attributes(G_vis, 'label')
nx.draw_networkx_edge_labels(G_vis, pos, edge_labels=edge_labels, font_color="darkred", font_size=8)

plt.title(f"Graphe RDF Amélioré - CV ID {resume_id}\nExtraction plus précise et filtrée", fontsize=18, pad=20)
plt.axis("off")
plt.tight_layout()
plt.show()

# 8. Export
# ------------------------------
g.serialize(destination=f"resume_graph_{resume_id}_improved.ttl", format="turtle")
print(f"Graphe exporté : resume_graph_{resume_id}_improved.ttl")

Une  version qui detecte mieux les enciens postes

# SUJET : Extraction améliorée d'entités CV → Graphe RDF + Visualisation propre
# =========================================================
!pip install kagglehub spacy rdflib networkx matplotlib
!python -m spacy download en_core_web_sm
import kagglehub
import os
import spacy
import networkx as nx
import matplotlib.pyplot as plt
import pandas as pd
import glob
import re
from rdflib import Graph, Namespace, Literal, RDF, RDFS, URIRef
from rdflib.namespace import FOAF, XSD

# 1. Chargement du CV
# ------------------------------
path = kagglehub.dataset_download("snehaanbhawal/resume-dataset")
csv_path = glob.glob(os.path.join(path, "**", "Resume.csv"), recursive=True)[0]
df = pd.read_csv(csv_path)
resume_text_column = 'Resume_str' if 'Resume_str' in df.columns else 'resume_str'

cv_index = 0  # Change ici pour tester un autre CV
row = df.iloc[cv_index]
resume_text_original = str(row[resume_text_column])  # original case
resume_text = resume_text_original.lower()  # lower for searches
resume_id = row.get('ID', cv_index + 1)

print(f"Analyse du CV n°{cv_index + 1} (ID: {resume_id})\n")

# 2. spaCy
# ------------------------------
nlp = spacy.load("en_core_web_sm")
doc = nlp(resume_text_original)

# 3. Namespaces RDF
# ------------------------------
EX = Namespace("http://example.org/resume/")
SCHEMA = Namespace("http://schema.org/")
g = Graph()
g.bind("ex", EX)
g.bind("schema", SCHEMA)
g.bind("foaf", FOAF)

resume_uri = EX[f"resume_{resume_id}"]
person_uri = EX[f"person_{resume_id}"]

g.add((resume_uri, RDF.type, SCHEMA.JobPosting))
g.add((resume_uri, SCHEMA.about, person_uri))
g.add((person_uri, RDF.type, FOAF.Person))

# 4. Listes enrichies et améliorées
# ------------------------------

# Compétences techniques et outils (on les cherche en priorité)
skills_list = [
    "python", "java", "javascript", "sql", "excel", "powerpoint", "tableau", "power bi", "r",
    "machine learning", "deep learning", "tensorflow", "pytorch", "aws", "azure", "gcp",
    "docker", "kubernetes", "git", "react", "angular", "node.js", "html", "css",
    "agile", "scrum", "devops", "ci/cd", "linux", "mongodb", "mysql", "postgresql",
    "rest api", "graphql", "jenkins", "terraform", "ansible", "spark", "hadoop", "big data"
]

# Postes / Rôles professionnels (enrichie avec plus de titres)
job_titles = [
    "data scientist", "software engineer", "machine learning engineer", "data analyst",
    "data engineer", "full stack developer", "frontend developer", "backend developer",
    "devops engineer", "cloud architect", "project manager", "product manager",
    "business analyst", "ux designer", "ui designer", "system administrator",
    "database administrator", "qa engineer", "security analyst", "hr manager", "recruiter",
    "hr administrator", "executive", "director", "assistant", "supervisor", "lead",
    "head", "technician", "representative", "associate", "coordinator", "officer",
    "front office manager", "reservation manager", "business administrator"
]

# Domaines d'études
fields_of_study = [
    "computer science", "data science", "information technology", "software engineering",
    "electrical engineering", "mechanical engineering", "business administration",
    "finance", "economics", "mathematics", "statistics", "physics", "psychology",
    "marketing", "human resources", "organizational leadership", "education",
    "artificial intelligence", "cybersecurity"
]

# ------------------------------
# 5. Extraction améliorée
# ------------------------------

# 1. Compétences (priorité haute : on les ajoute uniquement comme skills)
detected_skills = set()
for skill in skills_list:
    if skill in resume_text:
        detected_skills.add(skill.title())
        skill_uri = EX[f"skill_{skill.replace(' ', '_').replace('-', '_')}"]
        g.add((skill_uri, RDF.type, SCHEMA.Skill))
        g.add((skill_uri, RDFS.label, Literal(skill.title())))
        g.add((person_uri, SCHEMA.knowsAbout, skill_uri))  # plus approprié que hasSkill

# 2. Postes occupés (recherche plus large et multiple)
detected_jobs = set()
for title in job_titles:
    if title in resume_text:
        detected_jobs.add(title.title())
        g.add((person_uri, SCHEMA.jobTitle, Literal(title.title(), datatype=XSD.string)))

# Extraction améliorée de la section experience avec gestion des cas
experience_section_match = re.search(r'(?:professional\s+|work\s+)?experience\s*(.*?)(?=\s*(?:education|skills|summary|certifications|references|$))', resume_text, re.I | re.DOTALL)
if experience_section_match:
    start = experience_section_match.start(1)
    end = experience_section_match.end(1)
    exp_text_original = resume_text_original[start:end]
    if exp_text_original.strip():
        potential_titles = re.findall(r'(?:^|\n)\s*([A-Z][a-zA-Z\&\s]{10,80})(?:\s*,\s*|\s+at\s+|\s*\-|\s*\()', exp_text_original, re.M)
        for t in potential_titles:
            clean_title = t.strip().title()
            # Filtre : doit avoir au moins 2 mots, pas plus de 6, et ne pas ressembler à une entreprise (ex: pas "Inc", "LLC")
            words = clean_title.split()
            if 2 <= len(words) <= 6 and not any(word in ['Inc', 'LLC', 'Corp', 'Company'] for word in words):
                detected_jobs.add(clean_title)
                g.add((person_uri, SCHEMA.jobTitle, Literal(clean_title, datatype=XSD.string)))

# 3. Domaines d'études
detected_fields = set()
for field in fields_of_study:
    if field in resume_text:
        detected_fields.add(field.title())
        field_uri = EX[f"field_{field.replace(' ', '_')}"]
        g.add((field_uri, RDF.type, SCHEMA.EducationalOccupationalProgram))
        g.add((field_uri, SCHEMA.name, Literal(field.title())))
        g.add((person_uri, SCHEMA.alumniOf, field_uri))

# 4. Établissements éducatifs (via spaCy + filtre)
education_keywords = ["university", "college", "institute", "school"]
for ent in doc.ents:
    if ent.label_ == "ORG":
        ent_lower = ent.text.lower()
        if any(kw in ent_lower for kw in education_keywords) and "microsoft" not in ent_lower and "excel" not in ent_lower:
            org_uri = EX[f"edu_{ent.text.replace(' ', '_')}_{hash(ent.text) % 10000}"]
            g.add((org_uri, RDF.type, SCHEMA.CollegeOrUniversity))
            g.add((org_uri, SCHEMA.name, Literal(ent.text)))
            g.add((person_uri, SCHEMA.alumniOf, org_uri))

# 5. Organisations professionnelles (expérience pro, hors éducation et faux positifs)
blacklist_org = ["excel", "powerpoint", "word", "outlook", "customer", "state", "responsible", "agile"]
for ent in doc.ents:
    if ent.label_ == "ORG":
        ent_lower = ent.text.lower()
        if (any(kw in ent_lower for kw in education_keywords) or
            any(bl in ent_lower for bl in blacklist_org)):
            continue  # on saute les écoles (déjà traitées) et les faux positifs
        org_uri = EX[f"org_{ent.text.replace(' ', '_')}_{hash(ent.text) % 10000}"]
        g.add((org_uri, RDF.type, SCHEMA.Organization))
        g.add((org_uri, SCHEMA.name, Literal(ent.text)))
        g.add((person_uri, SCHEMA.worksFor, org_uri))  # plus précis que alumniOf

# ------------------------------
# 6. Affichage résumé
# ------------------------------
print("=== RÉSUMÉ DE L'EXTRACTION ===")
print(f"Compétences détectées : {', '.join(sorted(detected_skills)) or 'Aucune'}")
print(f"Postes occupés : {', '.join(sorted(detected_jobs)) or 'Aucun détecté précisément'}")
print(f"Domaines d'études : {', '.join(sorted(detected_fields)) or 'Aucun'}")
print(f"\nTotal triplets RDF : {len(g)}\n")

# ------------------------------
# 7. Visualisation améliorée (plus lisible)
# ------------------------------
G_vis = nx.DiGraph()
for s, p, o in g:
    s_label = str(s).split("/")[-1].replace("_", " ")[:30]
    if isinstance(o, URIRef):
        o_label = str(o).split("/")[-1].replace("_", " ")[:30]
    else:
        o_label = str(o)[:30]
    p_label = str(p).split("/")[-1].split("}")[-1]

    G_vis.add_node(s_label)
    G_vis.add_node(o_label)
    G_vis.add_edge(s_label, o_label, label=p_label)

plt.figure(figsize=(20, 14))
pos = nx.spring_layout(G_vis, k=2, iterations=100, seed=42)

# Couleurs par type
node_colors = []
for node in G_vis.nodes():
    if "person" in node.lower() or "resume" in node.lower():
        node_colors.append("#E74C3C")  # rouge pour la personne
    elif "skill" in node.lower():
        node_colors.append("#3498DB")  # bleu pour compétences
    elif "field" in node.lower() or "edu_" in node:
        node_colors.append("#2ECC71")  # vert pour éducation
    elif "org_" in node:
        node_colors.append("#F39C12")  # orange pour entreprises
    else:
        node_colors.append("#95A5A6")

nx.draw_networkx_nodes(G_vis, pos, node_color=node_colors, node_size=3000, edgecolors="black", linewidths=1.5)
nx.draw_networkx_edges(G_vis, pos, arrows=True, arrowstyle="->", arrowsize=20, width=1.2, alpha=0.7)
nx.draw_networkx_labels(G_vis, pos, font_size=9, font_weight="bold")
edge_labels = nx.get_edge_attributes(G_vis, 'label')
nx.draw_networkx_edge_labels(G_vis, pos, edge_labels=edge_labels, font_color="darkred", font_size=8)

plt.title(f"Graphe RDF Amélioré - CV ID {resume_id}\nExtraction plus précise et filtrée", fontsize=18, pad=20)
plt.axis("off")
plt.tight_layout()
plt.show()

# ------------------------------
# 8. Export
# ------------------------------
g.serialize(destination=f"resume_graph_{resume_id}_improved.ttl", format="turtle")
print(f"Graphe exporté : resume_graph_{resume_id}_improved.ttl")

"""**Correction du bug des faux skills (plus de "Head" ou "Keeps" en compétence)
Détection des dates d’expérience (années ou périodes comme "2015-2018", "Jan 2020 - Present", etc.)
Association poste ↔ entreprise quand c’est possible (ex: "Front Office Manager at Hotel X")
Meilleur nettoyage et déduplication des titres
Graphe encore plus riche et précis, toujours très lisible**
"""

# SUJET : Extraction améliorée d'entités CV → Graphe RDF + Visualisation propre
# =========================================================
!pip install kagglehub spacy rdflib networkx matplotlib
!python -m spacy download en_core_web_sm
import kagglehub
import os
import spacy
import networkx as nx
import matplotlib.pyplot as plt
import pandas as pd
import glob
import re
from rdflib import Graph, Namespace, Literal, RDF, RDFS, URIRef
from rdflib.namespace import FOAF, XSD

# 1. Chargement du CV
# ------------------------------
path = kagglehub.dataset_download("snehaanbhawal/resume-dataset")
csv_path = glob.glob(os.path.join(path, "**", "Resume.csv"), recursive=True)[0]
df = pd.read_csv(csv_path)
resume_text_column = 'Resume_str' if 'Resume_str' in df.columns else 'resume_str'

cv_index = 0  # Change ici pour tester un autre CV
row = df.iloc[cv_index]
resume_text = str(row[resume_text_column]).lower()  # tout en minuscule pour les recherches
resume_text_original = str(row[resume_text_column])  # garde l'original pour affichage
resume_id = row.get('ID', cv_index + 1)

print(f"Analyse du CV n°{cv_index + 1} (ID: {resume_id})\n")

# 2. spaCy

nlp = spacy.load("en_core_web_sm")
doc = nlp(resume_text_original)  # on garde le texte original pour spaCy (meilleure détection)

# 3. Namespaces RDF
# ------------------------------
EX = Namespace("http://example.org/resume/")
SCHEMA = Namespace("http://schema.org/")
g = Graph()
g.bind("ex", EX)
g.bind("schema", SCHEMA)
g.bind("foaf", FOAF)

resume_uri = EX[f"resume_{resume_id}"]
person_uri = EX[f"person_{resume_id}"]

g.add((resume_uri, RDF.type, SCHEMA.JobPosting))
g.add((resume_uri, SCHEMA.about, person_uri))
g.add((person_uri, RDF.type, FOAF.Person))


# 4. Listes enrichies et améliorées
# ------------------------------

# Compétences techniques et outils (on les cherche en priorité)
skills_list = [
    "python", "java", "javascript", "sql", "excel", "powerpoint", "tableau", "power bi", "r",
    "machine learning", "deep learning", "tensorflow", "pytorch", "aws", "azure", "gcp",
    "docker", "kubernetes", "git", "react", "angular", "node.js", "html", "css",
    "agile", "scrum", "devops", "ci/cd", "linux", "mongodb", "mysql", "postgresql",
    "rest api", "graphql", "jenkins", "terraform", "ansible", "spark", "hadoop", "big data"
]

# Postes / Rôles professionnels
job_titles = [
    "data scientist", "software engineer", "machine learning engineer", "data analyst",
    "data engineer", "full stack developer", "frontend developer", "backend developer",
    "devops engineer", "cloud architect", "project manager", "product manager",
    "business analyst", "ux designer", "ui designer", "system administrator",
    "database administrator", "qa engineer", "security analyst", "hr manager", "recruiter",
    "hr administrator", "executive", "director", "assistant", "supervisor", "lead",
    "head", "technician", "representative", "associate", "coordinator", "officer",
    "front office manager", "reservation manager", "business administrator"
]

# Domaines d'études
fields_of_study = [
    "computer science", "data science", "information technology", "software engineering",
    "electrical engineering", "mechanical engineering", "business administration",
    "finance", "economics", "mathematics", "statistics", "physics", "psychology",
    "marketing", "human resources", "organizational leadership", "education",
    "artificial intelligence", "cybersecurity"
]

# 5. Extraction améliorée
# ------------------------------

# 1. Compétences (priorité haute : on les ajoute uniquement comme skills)
detected_skills = set()
for skill in skills_list:
    if skill in resume_text:
        detected_skills.add(skill.title())
        skill_uri = EX[f"skill_{skill.replace(' ', '_').replace('-', '_')}"]
        g.add((skill_uri, RDF.type, SCHEMA.Skill))
        g.add((skill_uri, RDFS.label, Literal(skill.title())))
        g.add((person_uri, SCHEMA.knowsAbout, skill_uri))  # plus approprié que hasSkill

# 2. Postes occupés (version robuste)
detected_jobs = set()
for title in job_titles:
    if title in resume_text:
        detected_jobs.add(title.title())
        g.add((person_uri, SCHEMA.jobTitle, Literal(title.title(), datatype=XSD.string)))

# Extraction robuste dans section experience
experience_section_match = re.search(r'(?:professional\s+|work\s+)?experience\s*(.*?)(?=\s*(?:education|skills|summary|certifications|references|$))', resume_text, re.I | re.DOTALL)
if experience_section_match:
    exp_text = experience_section_match.group(1)
    exp_original = resume_text_original[experience_section_match.start(1):experience_section_match.end(1)]
    # Titres : phrases courtes en majuscules ou avec mots-clés
    title_patterns = re.findall(r'([A-Z][A-Za-z\s&]{10,80})(?:\s{2,}|\n|$)', exp_original, re.M)
    for t in title_patterns:
        clean_t = t.strip().title()
        if 2 <= len(clean_t.split()) <= 7 and any(kw in clean_t.lower() for kw in ["manager", "executive", "administrator", "supervisor", "lead", "officer", "coordinator"]):
            detected_jobs.add(clean_t)
            g.add((person_uri, SCHEMA.jobTitle, Literal(clean_t, datatype=XSD.string)))

# 3. Domaines d'études
detected_fields = set()
for field in fields_of_study:
    if field in resume_text:
        detected_fields.add(field.title())
        field_uri = EX[f"field_{field.replace(' ', '_')}"]
        g.add((field_uri, RDF.type, SCHEMA.EducationalOccupationalProgram))
        g.add((field_uri, SCHEMA.name, Literal(field.title())))
        g.add((person_uri, SCHEMA.alumniOf, field_uri))

# 4. Établissements éducatifs (via spaCy + filtre)
education_keywords = ["university", "college", "institute", "school"]
for ent in doc.ents:
    if ent.label_ == "ORG":
        ent_lower = ent.text.lower()
        if any(kw in ent_lower for kw in education_keywords) and "microsoft" not in ent_lower and "excel" not in ent_lower:
            org_uri = EX[f"edu_{ent.text.replace(' ', '_')}_{hash(ent.text) % 10000}"]
            g.add((org_uri, RDF.type, SCHEMA.CollegeOrUniversity))
            g.add((org_uri, SCHEMA.name, Literal(ent.text)))
            g.add((person_uri, SCHEMA.alumniOf, org_uri))

# 5. Organisations professionnelles (expérience pro, hors éducation et faux positifs)
blacklist_org = ["excel", "powerpoint", "word", "outlook", "customer", "state", "responsible", "agile"]
for ent in doc.ents:
    if ent.label_ == "ORG":
        ent_lower = ent.text.lower()
        if (any(kw in ent_lower for kw in education_keywords) or
            any(bl in ent_lower for bl in blacklist_org)):
            continue  # on saute les écoles (déjà traitées) et les faux positifs
        org_uri = EX[f"org_{ent.text.replace(' ', '_')}_{hash(ent.text) % 10000}"]
        g.add((org_uri, RDF.type, SCHEMA.Organization))
        g.add((org_uri, SCHEMA.name, Literal(ent.text)))
        g.add((person_uri, SCHEMA.worksFor, org_uri))  # plus précis que alumniOf

# 6. Affichage résumé
print("=== RÉSUMÉ DE L'EXTRACTION ===")
print(f"Compétences détectées : {', '.join(sorted(detected_skills)) or 'Aucune'}")
print(f"Postes occupés : {', '.join(sorted(detected_jobs)) or 'Aucun détecté précisément'}")
print(f"Domaines d'études : {', '.join(sorted(detected_fields)) or 'Aucun'}")
print(f"\nTotal triplets RDF : {len(g)}\n")

# 7. Visualisation améliorée (plus lisible)
G_vis = nx.DiGraph()
for s, p, o in g:
    s_label = str(s).split("/")[-1].replace("_", " ")[:30]
    if isinstance(o, URIRef):
        o_label = str(o).split("/")[-1].replace("_", " ")[:30]
    else:
        o_label = str(o)[:30]
    p_label = str(p).split("/")[-1].split("}")[-1]

    G_vis.add_node(s_label)
    G_vis.add_node(o_label)
    G_vis.add_edge(s_label, o_label, label=p_label)

plt.figure(figsize=(20, 14))
pos = nx.spring_layout(G_vis, k=2, iterations=100, seed=42)

# Couleurs par type
node_colors = []
for node in G_vis.nodes():
    if "person" in node.lower() or "resume" in node.lower():
        node_colors.append("#E74C3C")  # rouge pour la personne
    elif "skill" in node.lower():
        node_colors.append("#3498DB")  # bleu pour compétences
    elif "field" in node.lower() or "edu_" in node:
        node_colors.append("#2ECC71")  # vert pour éducation
    elif "org_" in node:
        node_colors.append("#F39C12")  # orange pour entreprises
    else:
        node_colors.append("#95A5A6")

nx.draw_networkx_nodes(G_vis, pos, node_color=node_colors, node_size=3000, edgecolors="black", linewidths=1.5)
nx.draw_networkx_edges(G_vis, pos, arrows=True, arrowstyle="->", arrowsize=20, width=1.2, alpha=0.7)
nx.draw_networkx_labels(G_vis, pos, font_size=9, font_weight="bold")
edge_labels = nx.get_edge_attributes(G_vis, 'label')
nx.draw_networkx_edge_labels(G_vis, pos, edge_labels=edge_labels, font_color="darkred", font_size=8)

plt.title(f"Graphe RDF Amélioré - CV ID {resume_id}\nExtraction plus précise et filtrée", fontsize=18, pad=20)
plt.axis("off")
plt.tight_layout()
plt.show()

# 8. Export
# ------------------------------
g.serialize(destination=f"resume_graph_{resume_id}_improved.ttl", format="turtle")
print(f"Graphe exporté : resume_graph_{resume_id}_improved.ttl")

"""**EXTRACTION DE DATES* PROBLEME TROP FRAGILE  MEILLEURE VISUALISATION POUR PAUFINNER  UNE PARTIE QUI RESUME LES CV S AFFICHE ON PEUT AVOIR DEUX TYPES D AFFICHAGES


"""

# =========================================================
# SUJET : Extraction complète CV → Graphe RDF enrichi + Résumé complet et correct
# =========================================================
!pip install kagglehub spacy rdflib networkx matplotlib
!python -m spacy download en_core_web_sm

import kagglehub
import os
import spacy
import networkx as nx
import matplotlib.pyplot as plt
import pandas as pd
import glob
import re
from rdflib import Graph, Namespace, Literal, RDF, RDFS, URIRef
from rdflib.namespace import FOAF, XSD

# ------------------------------
# 1. Chargement du CV
# ------------------------------
path = kagglehub.dataset_download("snehaanbhawal/resume-dataset")
csv_path = glob.glob(os.path.join(path, "**", "Resume.csv"), recursive=True)[0]
df = pd.read_csv(csv_path)
resume_text_column = 'Resume_str' if 'Resume_str' in df.columns else 'resume_str'

cv_index = 0  # Change ici pour tester un autre CV
row = df.iloc[cv_index]
resume_text = str(row[resume_text_column]).lower()  # minuscule pour recherches
resume_text_original = str(row[resume_text_column])  # original pour spaCy et affichage
resume_id = row.get('ID', cv_index + 1)

print(f"Analyse du CV n°{cv_index + 1} (ID: {resume_id})\n")

# 2. spaCy
nlp = spacy.load("en_core_web_sm")
doc = nlp(resume_text_original)


# 3. Namespaces RDF
EX = Namespace("http://example.org/resume/")
SCHEMA = Namespace("http://schema.org/")
g = Graph()
g.bind("ex", EX)
g.bind("schema", SCHEMA)
g.bind("foaf", FOAF)

resume_uri = EX[f"resume_{resume_id}"]
person_uri = EX[f"person_{resume_id}"]

g.add((resume_uri, RDF.type, SCHEMA.JobPosting))
g.add((resume_uri, SCHEMA.about, person_uri))
g.add((person_uri, RDF.type, FOAF.Person))


# 4. Listes enrichies
skills_list = [
    "python", "java", "javascript", "sql", "excel", "powerpoint", "tableau", "power bi", "r",
    "machine learning", "deep learning", "tensorflow", "pytorch", "aws", "azure", "gcp",
    "docker", "kubernetes", "git", "react", "angular", "node.js", "html", "css",
    "agile", "scrum", "devops", "ci/cd", "linux", "mongodb", "mysql", "postgresql",
    "rest api", "graphql", "jenkins", "terraform", "ansible", "spark", "hadoop", "big data"
]

job_titles = [
    "data scientist", "software engineer", "machine learning engineer", "data analyst",
    "data engineer", "full stack developer", "frontend developer", "backend developer",
    "devops engineer", "cloud architect", "project manager", "product manager",
    "business analyst", "ux designer", "ui designer", "system administrator",
    "database administrator", "qa engineer", "security analyst", "hr manager", "recruiter",
    "hr administrator", "executive", "director", "assistant", "supervisor", "lead",
    "head", "technician", "representative", "associate", "coordinator", "officer",
    "front office manager", "reservation manager", "business administrator"
]

fields_of_study = [
    "computer science", "data science", "information technology", "software engineering",
    "electrical engineering", "mechanical engineering", "business administration",
    "finance", "economics", "mathematics", "statistics", "physics", "psychology",
    "marketing", "human resources", "organizational leadership", "education",
    "artificial intelligence", "cybersecurity"
]


# 5. Extractions


# 1. Compétences
detected_skills = set()
for skill in skills_list:
    if skill in resume_text:
        clean_skill = skill.title()
        detected_skills.add(clean_skill)
        skill_uri = EX[f"skill_{skill.replace(' ', '_').replace('-', '_')}"]
        g.add((skill_uri, RDF.type, SCHEMA.Skill))
        g.add((skill_uri, RDFS.label, Literal(clean_skill)))
        g.add((person_uri, SCHEMA.knowsAbout, skill_uri))

# 2. Postes occupés (robuste)
detected_jobs = set()
for title in job_titles:
    if title in resume_text:
        clean_title = title.title()
        detected_jobs.add(clean_title)
        g.add((person_uri, SCHEMA.jobTitle, Literal(clean_title, datatype=XSD.string)))

# Extraction supplémentaire dans la section Experience
experience_match = re.search(r'(?:professional|work)?\s*experience\s*(.*?)(?=\s*(?:education|skills|summary|certifications|references|$))', resume_text, re.I | re.DOTALL)
if experience_match:
    exp_original = resume_text_original[experience_match.start(1):experience_match.end(1)]
    potential_titles = re.findall(r'^([A-Z][A-Za-z\s&,.\-]{8,70})(?:\n|$)', exp_original, re.M)
    for t in potential_titles:
        clean_t = t.strip().title()
        words = clean_t.split()
        if 2 <= len(words) <= 8 and any(kw in clean_t.lower() for kw in ["manager", "executive", "administrator", "supervisor", "lead", "officer", "coordinator", "analyst", "engineer", "specialist"]):
            detected_jobs.add(clean_t)
            g.add((person_uri, SCHEMA.jobTitle, Literal(clean_t, datatype=XSD.string)))

# 3. Domaines d'études
detected_fields = set()
for field in fields_of_study:
    if field in resume_text:
        clean_field = field.title()
        detected_fields.add(clean_field)
        field_uri = EX[f"field_{field.replace(' ', '_')}"]
        g.add((field_uri, RDF.type, SCHEMA.EducationalOccupationalProgram))
        g.add((field_uri, SCHEMA.name, Literal(clean_field)))
        g.add((person_uri, SCHEMA.alumniOf, field_uri))

# 4. Établissements éducatifs
education_keywords = ["university", "college", "institute", "school"]
for ent in doc.ents:
    if ent.label_ == "ORG":
        ent_lower = ent.text.lower()
        if any(kw in ent_lower for kw in education_keywords) and "microsoft" not in ent_lower and "excel" not in ent_lower:
            org_uri = EX[f"edu_{ent.text.replace(' ', '_')}_{hash(ent.text) % 10000}"]
            g.add((org_uri, RDF.type, SCHEMA.CollegeOrUniversity))
            g.add((org_uri, SCHEMA.name, Literal(ent.text)))
            g.add((person_uri, SCHEMA.alumniOf, org_uri))

# 5. Organisations professionnelles
blacklist_org = ["excel", "powerpoint", "word", "outlook", "customer", "state", "responsible", "agile", "power bi", "tableau"]
for ent in doc.ents:
    if ent.label_ == "ORG":
        ent_lower = ent.text.lower()
        if any(kw in ent_lower for kw in education_keywords) or any(bl in ent_lower for bl in blacklist_org):
            continue
        org_uri = EX[f"org_{ent.text.replace(' ', '_')}_{hash(ent.text) % 10000}"]
        g.add((org_uri, RDF.type, SCHEMA.Organization))
        g.add((org_uri, SCHEMA.name, Literal(ent.text)))
        g.add((person_uri, SCHEMA.worksFor, org_uri))


# 6. Résumé affiché (version qui marche toujours)

print("\n" + "="*60)
print("               RÉSUMÉ DU CV EXTRACTÉ")
print("="*60)

print(f"Candidat : Person ID {resume_id}")
print()

if detected_skills:
    print(f"Compétences clés ({len(detected_skills)} détectées) :")
    print("   " + ", ".join(sorted(detected_skills)))
else:
    print("Compétences clés : Aucune détectée")
print()

if detected_jobs:
    print(f"Postes occupés ({len(detected_jobs)} détectés) :")
    for job in sorted(detected_jobs):
        print(f"   • {job}")
else:
    print("Postes occupés : Aucun détecté")
print()

if detected_fields:
    print(f"Domaines d'études ({len(detected_fields)} détectés) :")
    print("   " + ", ".join(sorted(detected_fields)))
else:
    print("Domaines d'études : Aucun détecté")
print()

# On liste tous les literals reliés par alumniOf (même si pas de edu_)
alumni_literals = sorted(set(str(o) for s, p, o in g if p == SCHEMA.alumniOf))
if alumni_literals:
    print(f"Établissements ou domaines liés à l'éducation ({len(alumni_literals)} détectés) :")
    for item in alumni_literals:
        print(f"   • {item}")
else:
    print("Établissements ou domaines liés à l'éducation : Aucun détecté")
print()

# On liste tous les literals reliés par worksFor ou jobTitle (expérience pro)
work_literals = sorted(set(str(o) for s, p, o in g if p == SCHEMA.worksFor or (p == SCHEMA.jobTitle and "org_" not in str(s))))
if work_literals:
    print(f"Expérience professionnelle ou postes liés ({len(work_literals)} détectés) :")
    for item in work_literals:
        print(f"   • {item}")
else:
    print("Expérience professionnelle ou postes liés : Aucun détecté")
print()

print(f"Total de triplets RDF générés : {len(g)}")
print("="*60 + "\n")

# 7. Visualisation (labels visibles)
G_vis = nx.DiGraph()
for s, p, o in g:
    if isinstance(s, URIRef):
        s_label = str(s).split("/")[-1].replace("_", " ")
    else:
        s_label = str(s)

    if isinstance(o, URIRef):
        o_label = str(o).split("/")[-1].replace("_", " ")
    else:
        o_label = str(o)

    p_label = str(p).split("/")[-1].split("}")[-1] if "}" in str(p) else str(p).split("/")[-1]

    s_label = s_label[:40]
    o_label = o_label[:40]
    p_label = p_label[:30]

    G_vis.add_node(s_label)
    G_vis.add_node(o_label)
    G_vis.add_edge(s_label, o_label, label=p_label)

plt.figure(figsize=(24, 18))
pos = nx.spring_layout(G_vis, k=3, iterations=120, seed=42)

node_colors = []
for node in G_vis.nodes():
    low = node.lower()
    if "person" in low or "resume" in low:
        node_colors.append("#E74C3C")
    elif "skill" in low:
        node_colors.append("#3498DB")
    elif "field" in low or "edu_" in low:
        node_colors.append("#2ECC71")
    elif "org_" in low:
        node_colors.append("#F39C12")
    else:
        node_colors.append("#95A5A6")

nx.draw_networkx_nodes(G_vis, pos, node_color=node_colors, node_size=3500, edgecolors="black", linewidths=2)
nx.draw_networkx_edges(G_vis, pos, arrows=True, arrowstyle="->", arrowsize=25, width=1.5, alpha=0.8)
nx.draw_networkx_labels(G_vis, pos, font_size=10, font_weight="bold", font_family="sans-serif")

edge_labels = nx.get_edge_attributes(G_vis, 'label')
nx.draw_networkx_edge_labels(G_vis, pos, edge_labels=edge_labels, font_color="darkred", font_size=9, bbox=dict(facecolor='white', alpha=0.7, edgecolor='none'))

plt.title(f"Graphe RDF Complet - CV ID {resume_id}\nLabels visibles - Compétences, Postes, Études, Organisations", fontsize=20)
plt.axis("off")
plt.tight_layout()
plt.show()

# 8. Export
g.serialize(destination=f"resume_graph_{resume_id}_final.ttl", format="turtle")
print(f"Graphe RDF exporté : resume_graph_{resume_id}_final.ttl")



"""On a plus deux types d affichage pour la visualisation -> Homogénéisation"""

# SUJET : Extraction complète CV → Graphe RDF enrichi + Résumé complet et correct

!pip install kagglehub spacy rdflib networkx matplotlib
!python -m spacy download en_core_web_sm

import kagglehub
import os
import spacy
import networkx as nx
import matplotlib.pyplot as plt
import pandas as pd
import glob
import re
from rdflib import Graph, Namespace, Literal, RDF, RDFS, URIRef
from rdflib.namespace import FOAF, XSD

# 1. Chargement du CV
path = kagglehub.dataset_download("snehaanbhawal/resume-dataset")
csv_path = glob.glob(os.path.join(path, "**", "Resume.csv"), recursive=True)[0]
df = pd.read_csv(csv_path)
resume_text_column = 'Resume_str' if 'Resume_str' in df.columns else 'resume_str'

cv_index = 0  # Change ici pour tester un autre CV
row = df.iloc[cv_index]
resume_text = str(row[resume_text_column]).lower()  # minuscule pour recherches
resume_text_original = str(row[resume_text_column])  # original pour spaCy et affichage
resume_id = row.get('ID', cv_index + 1)

print(f"Analyse du CV n°{cv_index + 1} (ID: {resume_id})\n")

# 2. spaCy

nlp = spacy.load("en_core_web_sm")
doc = nlp(resume_text_original)

# 3. Namespaces RDF

EX = Namespace("http://example.org/resume/")
SCHEMA = Namespace("http://schema.org/")
g = Graph()
g.bind("ex", EX)
g.bind("schema", SCHEMA)
g.bind("foaf", FOAF)

resume_uri = EX[f"resume_{resume_id}"]
person_uri = EX[f"person_{resume_id}"]

g.add((resume_uri, RDF.type, SCHEMA.JobPosting))
g.add((resume_uri, SCHEMA.about, person_uri))
g.add((person_uri, RDF.type, FOAF.Person))


# 4. Listes enrichies

skills_list = [
    "python", "java", "javascript", "sql", "excel", "powerpoint", "tableau", "power bi", "r",
    "machine learning", "deep learning", "tensorflow", "pytorch", "aws", "azure", "gcp",
    "docker", "kubernetes", "git", "react", "angular", "node.js", "html", "css",
    "agile", "scrum", "devops", "ci/cd", "linux", "mongodb", "mysql", "postgresql",
    "rest api", "graphql", "jenkins", "terraform", "ansible", "spark", "hadoop", "big data"
]

job_titles = [
    "data scientist", "software engineer", "machine learning engineer", "data analyst",
    "data engineer", "full stack developer", "frontend developer", "backend developer",
    "devops engineer", "cloud architect", "project manager", "product manager",
    "business analyst", "ux designer", "ui designer", "system administrator",
    "database administrator", "qa engineer", "security analyst", "hr manager", "recruiter",
    "hr administrator", "executive", "director", "assistant", "supervisor", "lead",
    "head", "technician", "representative", "associate", "coordinator", "officer",
    "front office manager", "reservation manager", "business administrator"
]

fields_of_study = [
    "computer science", "data science", "information technology", "software engineering",
    "electrical engineering", "mechanical engineering", "business administration",
    "finance", "economics", "mathematics", "statistics", "physics", "psychology",
    "marketing", "human resources", "organizational leadership", "education",
    "artificial intelligence", "cybersecurity"
]

# ------------------------------
# 5. Extractions
# ------------------------------

# 1. Compétences
detected_skills = set()
for skill in skills_list:
    if skill in resume_text:
        clean_skill = skill.title()
        detected_skills.add(clean_skill)
        skill_uri = EX[f"skill_{skill.replace(' ', '_').replace('-', '_')}"]
        g.add((skill_uri, RDF.type, SCHEMA.Skill))
        g.add((skill_uri, RDFS.label, Literal(clean_skill)))
        g.add((person_uri, SCHEMA.knowsAbout, skill_uri))

# 2. Postes occupés (robuste)
detected_jobs = set()
for title in job_titles:
    if title in resume_text:
        clean_title = title.title()
        detected_jobs.add(clean_title)
        g.add((person_uri, SCHEMA.jobTitle, Literal(clean_title, datatype=XSD.string)))

# Extraction supplémentaire dans la section Experience
experience_match = re.search(r'(?:professional|work)?\s*experience\s*(.*?)(?=\s*(?:education|skills|summary|certifications|references|$))', resume_text, re.I | re.DOTALL)
if experience_match:
    exp_original = resume_text_original[experience_match.start(1):experience_match.end(1)]
    potential_titles = re.findall(r'^([A-Z][A-Za-z\s&,.\-]{8,70})(?:\n|$)', exp_original, re.M)
    for t in potential_titles:
        clean_t = t.strip().title()
        words = clean_t.split()
        if 2 <= len(words) <= 8 and any(kw in clean_t.lower() for kw in ["manager", "executive", "administrator", "supervisor", "lead", "officer", "coordinator", "analyst", "engineer", "specialist"]):
            detected_jobs.add(clean_t)
            g.add((person_uri, SCHEMA.jobTitle, Literal(clean_t, datatype=XSD.string)))

# 3. Domaines d'études
detected_fields = set()
for field in fields_of_study:
    if field in resume_text:
        clean_field = field.title()
        detected_fields.add(clean_field)
        field_uri = EX[f"field_{field.replace(' ', '_')}"]
        g.add((field_uri, RDF.type, SCHEMA.EducationalOccupationalProgram))
        g.add((field_uri, SCHEMA.name, Literal(clean_field)))
        g.add((person_uri, SCHEMA.alumniOf, field_uri))

# 4. Établissements éducatifs
education_keywords = ["university", "college", "institute", "school"]
for ent in doc.ents:
    if ent.label_ == "ORG":
        ent_lower = ent.text.lower()
        if any(kw in ent_lower for kw in education_keywords) and "microsoft" not in ent_lower and "excel" not in ent_lower:
            org_uri = EX[f"edu_{ent.text.replace(' ', '_')}_{hash(ent.text) % 10000}"]
            g.add((org_uri, RDF.type, SCHEMA.CollegeOrUniversity))
            g.add((org_uri, SCHEMA.name, Literal(ent.text)))
            g.add((person_uri, SCHEMA.alumniOf, org_uri))

# 5. Organisations professionnelles
blacklist_org = ["excel", "powerpoint", "word", "outlook", "customer", "state", "responsible", "agile", "power bi", "tableau"]
for ent in doc.ents:
    if ent.label_ == "ORG":
        ent_lower = ent.text.lower()
        if any(kw in ent_lower for kw in education_keywords) or any(bl in ent_lower for bl in blacklist_org):
            continue
        org_uri = EX[f"org_{ent.text.replace(' ', '_')}_{hash(ent.text) % 10000}"]
        g.add((org_uri, RDF.type, SCHEMA.Organization))
        g.add((org_uri, SCHEMA.name, Literal(ent.text)))
        g.add((person_uri, SCHEMA.worksFor, org_uri))

# ------------------------------
# 6. Résumé affiché (version finale propre et sans doublons)
# ------------------------------
print("\n" + "="*60)
print("               RÉSUMÉ DU CV EXTRACTÉ")
print("="*60)

print(f"Candidat : Person ID {resume_id}")
print()

# Compétences
if detected_skills:
    print(f"Compétences clés ({len(detected_skills)} détectées) :")
    print("   " + ", ".join(sorted(detected_skills)))
else:
    print("Compétences clés : Aucune détectée")
print()

# Postes occupés (propres, sans doublons)
if detected_jobs:
    print(f"Postes occupés ({len(detected_jobs)} détectés) :")
    for job in sorted(detected_jobs):
        print(f"   • {job}")
else:
    print("Postes occupés : Aucun détecté")
print()

# Domaines d'études
if detected_fields:
    print(f"Domaines d'études ({len(detected_fields)} détectés) :")
    print("   " + ", ".join(sorted(detected_fields)))
else:
    print("Domaines d'études : Aucun détecté")
print()

# Établissements éducatifs (nettoyés)
edu_names = set()
for s, p, o in g:
    if p == SCHEMA.alumniOf:
        name = str(o)
        # Si c'est un domaine d'étude (field_), on l'ignore ici
        if "field_" in str(s):
            continue
        # Nettoyage du nom
        name = re.sub(r"\s+\d+$", "", name)  # enlève le hash
        name = name.replace("_", " ")
        edu_names.add(name.strip())

if edu_names:
    print(f"Établissements fréquentés ({len(edu_names)} détectés) :")
    for edu in sorted(edu_names):
        print(f"   • {edu}")
else:
    print("Établissements fréquentés : Aucun détecté")
print()

# Organisations professionnelles (nettoyées)
org_names = set()
for s, p, o in g:
    if p == SCHEMA.worksFor or ("org_" in str(s) and p == SCHEMA.name):
        name = str(o)
        name = re.sub(r"\s+\d+$", "", name)
        name = name.replace("_", " ")
        org_names.add(name.strip())

if org_names:
    print(f"Expérience professionnelle dans ({len(org_names)} organisations détectées) :")
    for org in sorted(org_names):
        print(f"   • {org}")
else:
    print("Expérience professionnelle : Aucune organisation détectée")
print()

print(f"Total de triplets RDF générés : {len(g)}")
print("="*60 + "\n")
# 7. Visualisation (labels visibles)
# ------------------------------
G_vis = nx.DiGraph()
for s, p, o in g:
    if isinstance(s, URIRef):
        s_label = str(s).split("/")[-1].replace("_", " ")
    else:
        s_label = str(s)

    if isinstance(o, URIRef):
        o_label = str(o).split("/")[-1].replace("_", " ")
    else:
        o_label = str(o)

    p_label = str(p).split("/")[-1].split("}")[-1] if "}" in str(p) else str(p).split("/")[-1]

    s_label = s_label[:40]
    o_label = o_label[:40]
    p_label = p_label[:30]

    G_vis.add_node(s_label)
    G_vis.add_node(o_label)
    G_vis.add_edge(s_label, o_label, label=p_label)

plt.figure(figsize=(24, 18))
pos = nx.spring_layout(G_vis, k=3, iterations=120, seed=42)

node_colors = []
for node in G_vis.nodes():
    low = node.lower()
    if "person" in low or "resume" in low:
        node_colors.append("#E74C3C")
    elif "skill" in low:
        node_colors.append("#3498DB")
    elif "field" in low or "edu_" in low:
        node_colors.append("#2ECC71")
    elif "org_" in low:
        node_colors.append("#F39C12")
    else:
        node_colors.append("#95A5A6")

nx.draw_networkx_nodes(G_vis, pos, node_color=node_colors, node_size=3500, edgecolors="black", linewidths=2)
nx.draw_networkx_edges(G_vis, pos, arrows=True, arrowstyle="->", arrowsize=25, width=1.5, alpha=0.8)
nx.draw_networkx_labels(G_vis, pos, font_size=10, font_weight="bold", font_family="sans-serif")

edge_labels = nx.get_edge_attributes(G_vis, 'label')
nx.draw_networkx_edge_labels(G_vis, pos, edge_labels=edge_labels, font_color="darkred", font_size=9, bbox=dict(facecolor='white', alpha=0.7, edgecolor='none'))

plt.title(f"Graphe RDF Complet - CV ID {resume_id}\nLabels visibles - Compétences, Postes, Études, Organisations", fontsize=20)
plt.axis("off")
plt.tight_layout()
plt.show()

# 8. Export
# ------------------------------
g.serialize(destination=f"resume_graph_{resume_id}_final.ttl", format="turtle")
print(f"Graphe RDF exporté : resume_graph_{resume_id}_final.ttl")

"""**Essayer d'afficher un graphe globale en dessus du cas par cas **"""

!pip install kagglehub spacy rdflib networkx matplotlib
!python -m spacy download en_core_web_sm

import kagglehub
import os
import spacy
import networkx as nx
import matplotlib.pyplot as plt
import pandas as pd
import glob
import re
from rdflib import Graph, Namespace, Literal, RDF, RDFS, URIRef
from rdflib.namespace import FOAF, XSD

# 1. Chargement du dataset complet
path = kagglehub.dataset_download("snehaanbhawal/resume-dataset")
csv_path = glob.glob(os.path.join(path, "**", "Resume.csv"), recursive=True)[0]
df = pd.read_csv(csv_path)
resume_text_column = 'Resume_str' if 'Resume_str' in df.columns else 'resume_str'

print(f"Dataset chargé : {len(df)} CVs au total\n")

# 2. spaCy et namespaces
nlp = spacy.load("en_core_web_sm")

EX = Namespace("http://example.org/resume/")
SCHEMA = Namespace("http://schema.org/")

# Listes enrichies
skills_list = [
    "python", "java", "javascript", "sql", "excel", "powerpoint", "tableau", "power bi", "r",
    "machine learning", "deep learning", "tensorflow", "pytorch", "aws", "azure", "gcp",
    "docker", "kubernetes", "git", "react", "angular", "node.js", "html", "css",
    "agile", "scrum", "devops", "ci/cd", "linux", "mongodb", "mysql", "postgresql",
    "rest api", "graphql", "jenkins", "terraform", "ansible", "spark", "hadoop", "big data"
]

job_titles = [
    "data scientist", "software engineer", "machine learning engineer", "data analyst",
    "data engineer", "full stack developer", "frontend developer", "backend developer",
    "devops engineer", "cloud architect", "project manager", "product manager",
    "business analyst", "ux designer", "ui designer", "system administrator",
    "database administrator", "qa engineer", "security analyst", "hr manager", "recruiter",
    "hr administrator", "executive", "director", "assistant", "supervisor", "lead",
    "head", "technician", "representative", "associate", "coordinator", "officer",
    "front office manager", "reservation manager", "business administrator"
]

fields_of_study = [
    "computer science", "data science", "information technology", "software engineering",
    "electrical engineering", "mechanical engineering", "business administration",
    "finance", "economics", "mathematics", "statistics", "physics", "psychology",
    "marketing", "human resources", "organizational leadership", "education",
    "artificial intelligence", "cybersecurity"
]

education_keywords = ["university", "college", "institute", "school"]
blacklist_org = ["excel", "powerpoint", "word", "outlook", "customer", "state", "responsible", "agile", "power bi", "tableau"]


# 3. Construction du graphe GLOBAL
# ------------------------------
global_graph = Graph()
global_graph.bind("ex", EX)
global_graph.bind("schema", SCHEMA)
global_graph.bind("foaf", FOAF)

skill_uris = {}
field_uris = {}
org_uris = {}
edu_uris = {}

print("Construction du graphe global sur tous les CVs... (cela peut prendre quelques minutes)")

for idx, row in df.iterrows():
    resume_text = str(row[resume_text_column]).lower()
    resume_text_original = str(row[resume_text_column])
    resume_id = row.get('ID', idx + 1)

    person_uri = EX[f"person_{resume_id}"]
    global_graph.add((person_uri, RDF.type, FOAF.Person))

    doc = nlp(resume_text_original)

    # Compétences
    for skill in skills_list:
        if skill in resume_text:
            clean_skill = skill.title()
            if clean_skill not in skill_uris:
                skill_uri = EX[f"skill_{skill.replace(' ', '_').replace('-', '_')}"]
                skill_uris[clean_skill] = skill_uri
                global_graph.add((skill_uri, RDF.type, SCHEMA.Skill))
                global_graph.add((skill_uri, RDFS.label, Literal(clean_skill)))
            global_graph.add((person_uri, SCHEMA.knowsAbout, skill_uris[clean_skill]))

    # Postes occupés
    for title in job_titles:
        if title in resume_text:
            clean_title = title.title()
            global_graph.add((person_uri, SCHEMA.jobTitle, Literal(clean_title, datatype=XSD.string)))

    # Domaines d'études
    for field in fields_of_study:
        if field in resume_text:
            clean_field = field.title()
            if clean_field not in field_uris:
                field_uri = EX[f"field_{field.replace(' ', '_')}_{hash(field) % 10000}"]
                field_uris[clean_field] = field_uri
                global_graph.add((field_uri, RDF.type, SCHEMA.EducationalOccupationalProgram))
                global_graph.add((field_uri, SCHEMA.name, Literal(clean_field)))
            global_graph.add((person_uri, SCHEMA.alumniOf, field_uris[clean_field]))

    # Établissements éducatifs
    for ent in doc.ents:
        if ent.label_ == "ORG":
            ent_lower = ent.text.lower()
            if any(kw in ent_lower for kw in education_keywords) and all(bl not in ent_lower for bl in blacklist_org):
                clean_name = ent.text.strip()
                key = clean_name.lower()
                if key not in edu_uris:
                    edu_uri = EX[f"edu_{ent.text.replace(' ', '_')}_{hash(ent.text) % 10000}"]
                    edu_uris[key] = edu_uri
                    global_graph.add((edu_uri, RDF.type, SCHEMA.CollegeOrUniversity))
                    global_graph.add((edu_uri, SCHEMA.name, Literal(clean_name)))
                global_graph.add((person_uri, SCHEMA.alumniOf, edu_uris[key]))

    # Organisations professionnelles
    for ent in doc.ents:
        if ent.label_ == "ORG":
            ent_lower = ent.text.lower()
            if any(kw in ent_lower for kw in education_keywords) or any(bl in ent_lower for bl in blacklist_org):
                continue
            clean_name = ent.text.strip()
            key = clean_name.lower()
            if key not in org_uris:
                org_uri = EX[f"org_{ent.text.replace(' ', '_')}_{hash(ent.text) % 10000}"]
                org_uris[key] = org_uri
                global_graph.add((org_uri, RDF.type, SCHEMA.Organization))
                global_graph.add((org_uri, SCHEMA.name, Literal(clean_name)))
            global_graph.add((person_uri, SCHEMA.worksFor, org_uris[key]))

print(f"Graphe global construit : {len(global_graph)} triplets sur {len(df)} CVs\n")

# ==================================================================
# 4. Analyse détaillée d'un CV individuel
v_index = 300  # Change ce nombre pour analyser un autre CV
row = df.iloc[cv_index]
resume_text = str(row[resume_text_column]).lower()
resume_text_original = str(row[resume_text_column])
resume_id = row.get('ID', cv_index + 1)

print(f"Analyse détaillée du CV n°{cv_index + 1} (ID: {resume_id})\n")

# Graphe individuel
g = Graph()
g.bind("ex", EX)
g.bind("schema", SCHEMA)
g.bind("foaf", FOAF)

resume_uri = EX[f"resume_{resume_id}"]
person_uri = EX[f"person_{resume_id}"]

g.add((resume_uri, RDF.type, SCHEMA.JobPosting))
g.add((resume_uri, SCHEMA.about, person_uri))
g.add((person_uri, RDF.type, FOAF.Person))

doc = nlp(resume_text_original)

# Extraction compétences
detected_skills = set()
for skill in skills_list:
    if skill in resume_text:
        clean_skill = skill.title()
        detected_skills.add(clean_skill)
        skill_uri = EX[f"skill_{skill.replace(' ', '_').replace('-', '_')}"]
        g.add((skill_uri, RDF.type, SCHEMA.Skill))
        g.add((skill_uri, RDFS.label, Literal(clean_skill)))
        g.add((person_uri, SCHEMA.knowsAbout, skill_uri))

# Extraction postes
detected_jobs = set()
for title in job_titles:
    if title in resume_text:
        clean_title = title.title()
        detected_jobs.add(clean_title)
        g.add((person_uri, SCHEMA.jobTitle, Literal(clean_title, datatype=XSD.string)))

experience_match = re.search(r'(?:professional|work)?\s*experience\s*(.*?)(?=\s*(?:education|skills|summary|certifications|references|$))', resume_text, re.I | re.DOTALL)
if experience_match:
    exp_original = resume_text_original[experience_match.start(1):experience_match.end(1)]
    potential_titles = re.findall(r'^([A-Z][A-Za-z\s&,.\-]{8,70})(?:\n|$)', exp_original, re.M)
    for t in potential_titles:
        clean_t = t.strip().title()
        words = clean_t.split()
        if 2 <= len(words) <= 8 and any(kw in clean_t.lower() for kw in ["manager", "executive", "administrator", "supervisor", "lead", "officer", "coordinator", "analyst", "engineer", "specialist"]):
            detected_jobs.add(clean_t)
            g.add((person_uri, SCHEMA.jobTitle, Literal(clean_t, datatype=XSD.string)))

# Domaines d'études
detected_fields = set()
for field in fields_of_study:
    if field in resume_text:
        clean_field = field.title()
        detected_fields.add(clean_field)
        field_uri = EX[f"field_{field.replace(' ', '_')}"]
        g.add((field_uri, RDF.type, SCHEMA.EducationalOccupationalProgram))
        g.add((field_uri, SCHEMA.name, Literal(clean_field)))
        g.add((person_uri, SCHEMA.alumniOf, field_uri))

# Établissements éducatifs + Organisations (comme avant)
for ent in doc.ents:
    if ent.label_ == "ORG":
        ent_lower = ent.text.lower()
        if any(kw in ent_lower for kw in education_keywords) and all(bl not in ent_lower for bl in blacklist_org):
            org_uri = EX[f"edu_{ent.text.replace(' ', '_')}_{hash(ent.text) % 10000}"]
            g.add((org_uri, RDF.type, SCHEMA.CollegeOrUniversity))
            g.add((org_uri, SCHEMA.name, Literal(ent.text)))
            g.add((person_uri, SCHEMA.alumniOf, org_uri))
        elif not any(bl in ent_lower for bl in blacklist_org):
            org_uri = EX[f"org_{ent.text.replace(' ', '_')}_{hash(ent.text) % 10000}"]
            g.add((org_uri, RDF.type, SCHEMA.Organization))
            g.add((org_uri, SCHEMA.name, Literal(ent.text)))
            g.add((person_uri, SCHEMA.worksFor, org_uri))

# ------------------------------
# 5. Résumé textuel du CV individuel
# ------------------------------
print("\n" + "="*60)
print("               RÉSUMÉ DU CV EXTRACTÉ")
print("="*60)

print(f"Candidat : Person ID {resume_id}\n")

if detected_skills:
    print(f"Compétences clés ({len(detected_skills)}) :")
    print("   " + ", ".join(sorted(detected_skills)))
else:
    print("Compétences clés : Aucune détectée")
print()

if detected_jobs:
    print(f"Postes occupés ({len(detected_jobs)}) :")
    for job in sorted(detected_jobs):
        print(f"   • {job}")
else:
    print("Postes occupés : Aucun détecté")
print()

if detected_fields:
    print(f"Domaines d'études ({len(detected_fields)}) :")
    print("   " + ", ".join(sorted(detected_fields)))
else:
    print("Domaines d'études : Aucun détecté")
print()

# Établissements
edu_names = {str(o) for s, p, o in g if p == SCHEMA.alumniOf and "field_" not in str(s)}
edu_names = {re.sub(r"\s+\d+$", "", n).replace("_", " ").strip() for n in edu_names}
if edu_names:
    print(f"Établissements fréquentés ({len(edu_names)}) :")
    for edu in sorted(edu_names):
        print(f"   • {edu}")
else:
    print("Établissements fréquentés : Aucun détecté")
print()

# Organisations pro
org_names = {str(o) for s, p, o in g if p == SCHEMA.worksFor or ("org_" in str(s) and p == SCHEMA.name)}
org_names = {re.sub(r"\s+\d+$", "", n).replace("_", " ").strip() for n in org_names}
if org_names:
    print(f"Expérience professionnelle dans ({len(org_names)} organisations) :")
    for org in sorted(org_names):
        print(f"   • {org}")
else:
    print("Expérience professionnelle : Aucune organisation détectée")
print()

print(f"Total de triplets RDF (CV individuel) : {len(g)}")
print("="*60 + "\n")


# 6. Visualisation du graphe individuel
# ------------------------------
G_vis = nx.DiGraph()
for s, p, o in g:
    s_label = str(s).split("/")[-1].replace("_", " ")[:40]
    o_label = str(o).split("/")[-1].replace("_", " ")[:40] if isinstance(o, URIRef) else str(o)[:40]
    p_label = str(p).split("/")[-1][:30]

    G_vis.add_node(s_label)
    G_vis.add_node(o_label)
    G_vis.add_edge(s_label, o_label, label=p_label)

plt.figure(figsize=(24, 18))
pos = nx.spring_layout(G_vis, k=3, iterations=120, seed=42)

node_colors = []
for node in G_vis.nodes():
    low = node.lower()
    if "person" in low or "resume" in low:
        node_colors.append("#E74C3C")
    elif "skill" in low:
        node_colors.append("#3498DB")
    elif "field" in low or "edu_" in low:
        node_colors.append("#2ECC71")
    elif "org_" in low:
        node_colors.append("#F39C12")
    else:
        node_colors.append("#95A5A6")

nx.draw_networkx_nodes(G_vis, pos, node_color=node_colors, node_size=3500, edgecolors="black", linewidths=2)
nx.draw_networkx_edges(G_vis, pos, arrows=True, arrowstyle="->", arrowsize=25, width=1.5, alpha=0.8)
nx.draw_networkx_labels(G_vis, pos, font_size=10, font_weight="bold")
edge_labels = nx.get_edge_attributes(G_vis, 'label')
nx.draw_networkx_edge_labels(G_vis, pos, edge_labels=edge_labels, font_color="darkred", font_size=9,
                             bbox=dict(facecolor='white', alpha=0.7, edgecolor='none'))

plt.title(f"Graphe RDF - CV Individuel ID {resume_id}", fontsize=20)
plt.axis("off")
plt.tight_layout()
plt.show()

# Export graphe individuel
g.serialize(destination=f"resume_graph_{resume_id}_individual.ttl", format="turtle")
print(f"Graphe individuel exporté : resume_graph_{resume_id}_individual.ttl\n")

# ==================================================================
# 7. Visualisation du SCHÉMA GLOBAL (toute la base)
# ==================================================================
print("\n" + "="*80)
print("           SCHÉMA GLOBAL AGRÉGÉ DE TOUTE LA BASE DE DONNÉES")
print("="*80)

"""# STATS"""

# Nombre total de CVs
nb_cvs = len(df)
print(f"Nombre total de CVs analysés : {nb_cvs}")

# Nombre total de triplets RDF générés
nb_triplets = len(global_graph)
print(f"Nombre total de triplets RDF : {nb_triplets}")

from collections import defaultdict

skills_per_cv = defaultdict(int)
jobs_per_cv = defaultdict(int)
fields_per_cv = defaultdict(int)

for s, p, o in global_graph:
    s_str = str(s)
    if "person_" in s_str:
        if "knowsAbout" in str(p):
            skills_per_cv[s_str] += 1
        if "jobTitle" in str(p):
            jobs_per_cv[s_str] += 1
        if "alumniOf" in str(p):
            fields_per_cv[s_str] += 1

print(f"Compétences moyennes par CV : {sum(skills_per_cv.values())/nb_cvs:.2f}")
print(f"Postes moyens par CV : {sum(jobs_per_cv.values())/nb_cvs:.2f}")
print(f"Domaines d'études moyens par CV : {sum(fields_per_cv.values())/nb_cvs:.2f}")

from collections import Counter

skills_counter = Counter()
for s, p, o in global_graph:
    if "knowsAbout" in str(p):
        skills_counter[str(o)] += 1

print("Top 10 des compétences les plus fréquentes :")
for skill, count in skills_counter.most_common(10):
    print(f"{skill} : {count} CVs")

jobs_counter = Counter()
fields_counter = Counter()

for s, p, o in global_graph:
    if "jobTitle" in str(p):
        jobs_counter[str(o)] += 1
    if "alumniOf" in str(p) and "field_" in str(o):
        fields_counter[str(o)] += 1

print("Top 10 postes :")
for job, count in jobs_counter.most_common(10):
    print(f"{job} : {count} CVs")

print("Top 10 domaines :")
for field, count in fields_counter.most_common(10):
    print(f"{field} : {count} CVs")

import matplotlib.pyplot as plt

# Histogramme des compétences
top_skills = skills_counter.most_common(10)
labels, values = zip(*top_skills)
plt.figure(figsize=(10,6))
plt.barh(labels, values, color="#3498DB")
plt.gca().invert_yaxis()
plt.title("Top 10 compétences les plus fréquentes")
plt.show()

# Histogramme des postes
top_jobs = jobs_counter.most_common(10)
labels, values = zip(*top_jobs)
plt.figure(figsize=(10,6))
plt.barh(labels, values, color="#E74C3C")
plt.gca().invert_yaxis()
plt.title("Top 10 postes")
plt.show()

top_fields = fields_counter.most_common(10)
labels, values = zip(*top_fields)

plt.figure(figsize=(10,6))
plt.barh(labels, values, color="#2ECC71")
plt.gca().invert_yaxis()
plt.title("Top 10 domaines d’études")
plt.xlabel("Nombre de CVs")
plt.show()

import networkx as nx
import matplotlib.pyplot as plt

G_co = nx.Graph()

# On prend un échantillon de CV pour clarté visuelle
sample_df = df.sample(200, random_state=42)

for _, row in sample_df.iterrows():
    text = str(row[resume_text_column]).lower()
    jobs_found = [title.title() for title in job_titles if title in text]
    skills_found = [skill.title() for skill in skills_list if skill in text]
    for job in jobs_found:
        for skill in skills_found:
            G_co.add_edge(skill, job)

# Identifier type de nœud
node_colors = []
for node in G_co.nodes():
    if node in [skill.title() for skill in skills_list]:
        node_colors.append("#3498DB")  # bleu pour compétences
    else:
        node_colors.append("#E74C3C")  # rouge pour postes

plt.figure(figsize=(14,10))
pos = nx.spring_layout(G_co, k=0.7, seed=42)
nx.draw(G_co, pos, with_labels=True, node_size=2000, node_color=node_colors,
        font_size=9, font_weight="bold", edge_color="#34495E", alpha=0.7)
plt.title("Graphe de co-occurrence Compétences ↔ Postes (échantillon 200 CVs)", fontsize=16)
plt.show()

skills_counts = [len([skill for skill in skills_list if skill in str(row[resume_text_column]).lower()]) for _, row in df.iterrows()]

plt.figure(figsize=(10,6))
plt.hist(skills_counts, bins=15, color="#3498DB", edgecolor="black")
plt.title("Distribution du nombre de compétences par CV")
plt.xlabel("Nombre de compétences détectées")
plt.ylabel("Nombre de CVs")
plt.show()

jobs_counts = [len([title for title in job_titles if title in str(row[resume_text_column]).lower()]) for _, row in df.iterrows()]

plt.figure(figsize=(10,6))
plt.hist(jobs_counts, bins=15, color="#E74C3C", edgecolor="black")
plt.title("Distribution du nombre de postes détectés par CV")
plt.xlabel("Nombre de postes")
plt.ylabel("Nombre de CVs")
plt.show()

fields_counts = [len([field for field in fields_of_study if field in str(row[resume_text_column]).lower()]) for _, row in df.iterrows()]

plt.figure(figsize=(10,6))
plt.hist(fields_counts, bins=15, color="#2ECC71", edgecolor="black")
plt.title("Distribution du nombre de domaines d'études par CV")
plt.xlabel("Nombre de domaines détectés")
plt.ylabel("Nombre de CVs")
plt.show()

import matplotlib.pyplot as plt

# Comptage des CVs par catégorie
category_counts = df['Category'].value_counts()

# Diagramme circulaire
plt.figure(figsize=(10, 8))
plt.pie(category_counts, labels=category_counts.index, autopct='%1.1f%%', startangle=140, colors=plt.cm.tab20.colors)
plt.title("Répartition des CVs par catégorie", fontsize=16)
plt.axis('equal')  # Cercle parfait
plt.show()

